accent = "#ebbcba"
active_border_color = "#c4a7e7"
active_tab_background = "#403d52"

cursor = "#e0def4"
foreground = "#e0def4"
background = "#191724"
selection_foreground = "#e0def4"
selection_background = "#403d52"

color0 = "#26233a"
color1 = "#eb6f92"
color2 = "#31748f"
color3 = "#f6c177"
color4 = "#9ccfd8"
color5 = "#c4a7e7"
color6 = "#ebbcba"
color7 = "#e0def4"
color8 = "#6e6a86"
color9 = "#eb6f92"
color10 = "#31748f"
color11 = "#f6c177"
color12 = "#9ccfd8"
color13 = "#c4a7e7"
color14 = "#ebbcba"
color15 = "#e0def4"

