[tools]
ruby = "4.0.0"
nodejs = "latest"
zig = "latest"
rust = "latest"
go = "latest"
node = "latest"
bun = "latest"
fnox = "latest"
python = "latest"

[settings]
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = "1 week"
not_found_auto_install = true
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
