## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: Ros√© Pine
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)



"text"      = { fg = "#e0def4", bg = "#191724" }
"dimmed"    = { fg = "#6e6a86", bg = "#191724" }
"title"     = { fg = "#c4a7e7", bold = true }
"shortcut"  = { fg = "#f6c177" }
"matched"   = { fg = "#ebbcba" }
"border"    = { fg = "#6e6a86" }
"selected"  = { bg = "#1f1d2e", fg = "#e0def4", bold = true }

"source_marker" = { bg = "#9ccfd8", fg = "#191724", bold = true }
"target_marker" = { bg = "#31748f", fg = "#191724", bold = true }

"status" = { bg = "#1f1d2e" }
"status title" = { fg = "#191724", bg = "#c4a7e7", bold = true }

"revset title" = { fg = "#c4a7e7", bold = true }
"revset text" = { fg = "#e0def4", bold = true }
"revset completion text" = { fg = "#e0def4" }
"revset completion matched" = { fg = "#ebbcba", bold = true }
"revset completion dimmed" = { fg = "#6e6a86" }
"revset completion selected" = { bg = "#26233a", fg = "#e0def4" }

"revisions" = { fg = "#e0def4" }
"revisions selected" = { bg = "#1f1d2e"}
"revisions dimmed" = { fg = "#6e6a86" }
"revisions details selected" = { bg = "#26233a" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#e0def4" }
"evolog selected" = { bg = "#26233a", fg = "#e0def4", bold = true }

"menu" = { bg = "#191724" }
"menu title" = { fg = "#191724", bg = "#f6c177", bold = true }
"menu shortcut" = { fg = "#f6c177" }
"menu matched" = { fg = "#ebbcba", bold = true }
"menu dimmed" = { fg = "#6e6a86" }
"menu border" = { fg = "#1f1d2e" }
"menu selected" = { bg = "#26233a", fg = "#e0def4" }

"help" = { bg = "#191724" }
"help title" = { fg = "#31748f", bold = true, underline = true }
"help border" = { fg = "#1f1d2e" }

"preview" = { fg = "#e0def4" }
"preview border" = { fg = "#1f1d2e" }

"confirmation" = { bg = "#191724" }
"confirmation text" = { fg = "#c4a7e7", bold = true }
"confirmation dimmed" = { fg = "#6e6a86" }
"confirmation border" = { fg = "#eb6f92", bold = true }
"confirmation selected" = { bg = "#26233a", fg = "#e0def4" }

"undo" = { bg = "#191724" }
"undo confirmation dimmed" = { fg = "#6e6a86" }
"undo confirmation selected" = { bg = "#26233a", fg = "#e0def4" }

"success" = { fg = "#31748f", bold = true }
"error" = { fg = "#eb6f92", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#f6c177" }
"status dimmed" = { fg = "#6e6a86" }

"details" = { fg = "#e0def4" }
"details selected" = { bold = true }
"completion" = { fg = "#e0def4" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#c4a7e7" }
"branch" = { fg = "#f6c177" }
"commit" = { fg = "#31748f" }
"file" = { fg = "#ebbcba" }
"change" = { fg = "#eb6f92" }
"bookmark" = { fg = "#f6c177" }

